name: CI/CD for Spring Boot Application

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # 1.1 리포지토리 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 1.2 Gradle 실행 권한 부여
    - name: Give Gradle wrapper execute permission
      run: chmod +x ./gradlew

    # 1.3 Java 버전 설정
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 1.4 Gradle 빌드 실행
    - name: Build with Gradle
      run: |
        ./gradlew clean build
    # 1.5 빌드 결과물 전송 (SCP 명령어 사용)
    - name: Upload build artifact to Lightsail
      env:
        LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
        LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
      run: |
        echo "${LIGHTSAIL_SSH_KEY}" > lightsail.pem
        chmod 600 lightsail.pem  # 권한 설정
        scp -i lightsail.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build/libs/*.jar ${LIGHTSAIL_USERNAME}@${LIGHTSAIL_HOST}:/home/${LIGHTSAIL_USERNAME}/app/
        rm lightsail.pem
    # 1.6 권한 설정 (애플리케이션 실행 전)
   # - name: Set permissions for app directory and log files
    #  run: |
     #   chmod -R 755 /home/${LIGHTSAIL_USERNAME}/app/
      #  chmod 777 /home/${LIGHTSAIL_USERNAME}/app/app.log


    # 1.7 Lightsail에서 애플리케이션 실행
    - name: Start application on Lightsail
      env:
        LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
        LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
      run: |
        echo "${LIGHTSAIL_SSH_KEY}" > lightsail.pem
        chmod 600 lightsail.pem  # 권한 설정
        ssh -i lightsail.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${LIGHTSAIL_USERNAME}@${LIGHTSAIL_HOST} << 'EOF'
          # 기존 실행 중인 Java 애플리케이션 종료
        echo "Stopping existing Java application..."
        pkill -f 'java -jar' || true
        
        # 종료된 프로세스 확인
        echo "Checking if Java processes are still running..."
        ps aux | grep java
        
        # 새 애플리케이션 실행 (로그 파일로 리디렉션)
        echo "Starting new Java application..."
        nohup java -jar cicd-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
        
        # 새 애플리케이션 실행 후 프로세스 확인
        echo "Checking if new Java application is running..."
        ps aux | grep java
        
        # 세션 분리
        disown
        
        # 종료 상태 확인
        echo "Application started"


