name: CI/CD for Lightsail with Docker

on:
  push:
    branches:
      - master

jobs:
  # Job 1: Build Docker Image
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

        # Docker 26.1.3 버전 설치
      - name: Install Docker 26.1.3
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc  # 기존 Docker 제거
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce=5:26.1.3~3-0~ubuntu-$(lsb_release -cs) docker-ce-cli=5:26.1.3~3-0~ubuntu-$(lsb_release -cs) containerd.io
          docker --version  # 설치된 Docker 버전 확인

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Check Docker Version
        run: |
          docker --version  # Docker 버전 확인

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      - name: Save Docker Image as Tar
        run: |
          sudo mkdir -p /home/${{ secrets.LIGHTSAIL_USERNAME }}  # 디렉토리 생성
          sudo docker save my-app:latest -o /home/${{ secrets.LIGHTSAIL_USERNAME }}/my-app.tar
          sudo chmod 777 /home/${{ secrets.LIGHTSAIL_USERNAME }}/my-app.tar  # 모든 사용자에게 읽기/쓰기 권한 부여
          ls -lh /home/${{ secrets.LIGHTSAIL_USERNAME }}/my-app.tar  # 파일 존재 여부 확인




      - name: Upload Docker Tar Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-tar
          path: /home/ubuntu/my-app.tar  # 절대 경로로 지정


  # Job 2: Transfer Docker Image to Lightsail
  transfer:
    name: Transfer Docker Image
    runs-on: ubuntu-latest

    needs: build  # Dependency on the build job
    steps:
      - name: Download Docker Tar Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app-tar
  
      - name: Verify Downloaded File
        run: |
          echo "Verifying downloaded file:"
          ls -lh ./my-app.tar  # 디버깅용 확인

      - name: Transfer Docker Image to Lightsail
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: ./my-app.tar
          target: /home/${{ secrets.LIGHTSAIL_USERNAME }}/my-app.tar

      - name: Verify Transferred File on Lightsail
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            echo "Verifying transferred file on server:"
            ls -lh /home/${{ secrets.LIGHTSAIL_USERNAME }}/my-app.tar || exit 1

  # Job 3: Deploy Docker Container
  deploy:
    name: Deploy Docker Container
    runs-on: ubuntu-latest

    needs: transfer  # Dependency on the transfer job
    steps:
      - name: Run Docker Image on Lightsail
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            echo "Starting deployment process..."

            # Step 1: Load the Docker image
            echo "Loading Docker image..."
            docker load -i /home/${{ secrets.LIGHTSAIL_USERNAME }}/my-app.tar || exit 1

            # Step 2: Stop and remove existing container if any
            echo "Stopping and removing any existing container..."
            docker stop app || true
            docker rm app || true

            # Step 3: Run the container on port 8080
            echo "Running the container on port 8080..."
            docker run -d --name app -p 8080:8080 --restart unless-stopped my-app:latest || exit 1

            echo "Deployment completed successfully!"
